### ISSUE TITLE
Rename this trash to flagged reddit gen

### ISSUE THREAD

**Issue by Oli2004** [imvast/Reddit-Account-Creator#4]
you dont know shit whats so ever. reddit is harder than discord to gen without getting flagged/shadow banned in the week after the generation. also who the fuck uses captcha endpoint in 2024 💀  get a fucking brain and touch grass.

also Vast is a scammer. Nigga scammed for 50$ HOW BROKE DO YOU HAVE TO BE TO SCAM FOR 50 BUCKS?!

**Comment by cuddlycatgirl** [comment]
Z

**Comment by Euro-pol** [comment]
who did he scam for 50$

**Comment by imvast** [comment]
womp womp and show proof of scam rn LMAO

**Comment by imvast** [comment]
![image](https://github.com/imvast/Reddit-Account-Creator/assets/60797067/f95a2121-0180-4ba7-8bf0-5345a3beaf65)
proof of scam 🔥
